# Generated by Django 4.1.5 on 2023-02-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizpix', '0008_alter_game_difficulty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
