# Generated by Django 4.1.5 on 2023-02-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizpix', '0009_delete_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='quizzes_made',
            field=models.IntegerField(default=0),
        ),
    ]
