# Generated by Django 4.1.7 on 2023-03-06 13:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizpix', '0017_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=3),
        ),
    ]
