# Generated by Django 4.1.7 on 2023-03-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizpix', '0020_alter_question_choices_alter_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
