# Generated by Django 4.1.5 on 2023-01-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizpix', '0005_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
